name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  model_ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container:
    #   image: mcr.microsoft.com/mlops/python:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Run lint tests
    #   run: flake8 --output-file=lint-testresults.xml --format junit-xml

    # Runs Linting
    - name: Run a multi-line scriptsteps
      uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
      with:
        # The GitHub API token to create reviews with
        token: ${{ secrets.GIT_HUB_TOKEN }}
        # Fail if "new" violations detected or "any", default "new"
        failIf: any
