name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  model_ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: 
    #   image: mcr.microsoft.com/mlops/python:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Run lint tests
    #   run: flake8 --output-file=lint-testresults.xml --format junit-xml
    
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'model_ci'   # NOTE: this needs to be the same as the job name
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      if: always()
      with:
        # Artifact name
        name: Linting-report
        # Directory containing files to upload
        path: lint-testresults.xml

    # - uses: ashley-taylor/junit-report-annotations-action@v1.0
    #   if: always()
    #   with:
    #     access-token: ${{ secrets.GITHUB_TOKEN }}
    #     path: lint-testresults.xml
    # Runs Linting
    # - name: Run a multi-line scriptsteps
    #   uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
    #   with:
    #     # The GitHub API token to create reviews with
    #     token: ${{ secrets.GIT_HUB_TOKEN }}
    #     # Fail if "new" violations detected or "any", default "new"
    #     failIf: any
